### ISSUE TITLE
Deploy arsnova on a redhat 7 server

### ISSUE THREAD

**Issue by deada92** [thm-projects/arsnova-backend#28] opened 2015-11-19 14:20 UTC
Hello Arsnova-Team,

I'm part of the eLearning department of the Ruhr University Bochum. We are trying at the moment to build a standalone server for Arsnova. We also tried to contact Mr. Quibeldey-Cirkel unfornateley without luck.

I have to seperate my Problem in 2 question because I tried both ways that you guys wrote in the docs. So here we go:

**1. Vagrant Installation**
The installation on my local Mac is completed without any problems. I also could access Arsnova and use it like its supposed to. Still, I couldn't understand how this would help me. I need Arsnova to be deployed to a Virtual Server that is located in our Serverfarm and runs RedHat 7. 
**Is there any way to get this done with Vagrant?**

**2. Manuall Installation**
I tried to follow your docs but unfornatley it doesn't provide a guide to install it manually: Thats what I  have done yet:

- Erlang R14B01 (build from src)
- Mozilla Spidermonky (src)
- CouchDB 1.6.1
- Arsnova Python (tool) script runned successfully
- Arsnova backend on tomcat 7.0.34 deployed 
- Nodejs & npm
- Ruby
- Sencha 4.0.5.87
- Arsnova-mobile downloaded from github:
  - npm install -g grunt-cli
  - changed to /mobile directory
  - grunt package
**At this step I got following error:**
The application was last modified by an older version of Sencha Cmd (4.0.4.84) the current is 4.0.5.87. Please run "sencha app upgrade" to update to 4.0.5.87.
    - **When I try to update I get a Nullpointer..**

```
[root@vmrz0303 arsnova-mobile-master]# sencha app upgrade
Sencha Cmd v4.0.5.87
[ERR] java.lang.NullPointerException
     at java.util.regex.Matcher.getTextLength(Matcher.java:1151)
     at java.util.regex.Matcher.reset(Matcher.java:302)
     at java.util.regex.Matcher.<init>(Matcher.java:222)
     at java.util.regex.Pattern.matcher(Pattern.java:899)
     at com.sencha.util.Version.cleanVersionString(Version.java:169)
     at com.sencha.command.app.AppCommands$UpgradeCommand.execute(AppCommands.java:216)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
     at java.lang.reflect.Method.invoke(Method.java:611)
     at com.sencha.util.MethodInvoker$Arguments.invoke(MethodInvoker.java:175)
     at com.sencha.cli.Command.dispatch(Command.java:42)
     at com.sencha.cli.Commands.dispatch(Commands.java:64)
     at com.sencha.cli.Commands.dispatch(Commands.java:64)
     at com.sencha.command.Sencha.dispatch(Sencha.java:80)
     at com.sencha.command.Sencha.main(Sencha.java:148)
```

I really hope that you guys can help. We here in Bochum like this solution and would love to get in touch.

regards,

Saif

**Comment by commana** [comment] 2015-11-19 15:58
Thanks for your questions. Maybe deploying one of our release versions is an option for you? Then you won't need to fiddle with all the build tools.

As for your concrete problem, you probably need to downgrade to Sencha Cmd version 4.0.4.84. Also don't forget to run `npm install` the first time in `/mobile`.

**Comment by deada92** [comment] 2015-11-19 16:21
Hey @commana,

my second approach was based on the arsnova backend version 2.2.0 from the github release page. So I already did that..

Unfornatley I can't find sencha cmd 4.0.4.84... The only one tha is avalaible was 4.0.5.87

**Comment by commana** [comment] 2015-11-19 16:35
There is also a release for ARSnova mobile, so all you really need is CouchDB and Tomcat. See https://github.com/thm-projects/arsnova-mobile/releases

The Sencha CDN has all previous versions available, it's just not very prominent. Here is a link for your convenience: https://cdn.sencha.com/cmd/4.0.4.84/SenchaCmd-4.0.4.84-linux.run.zip

You can essentially change the two version strings found in the URL to the exact version you need.

**Comment by deada92** [comment] 2015-11-19 16:39
ty @commana,

I'll try tommorow do update and deploy the applications again.. I will tell you if it works tommorow :)

**Comment by deada92** [comment] 2015-11-20 08:35
Good morning @commana,

I took your advice and downloaded both release versions 2.2.0 of the backend and mobile application. I have setup the "arsnova.properties" file in /etc/arsnova/ with my CouchDB credentials.

Unfornatley when I visit the application it loads (the loading bubbles) first and then says that the connection to the Server couldn't be build (atleast I dont get a blank a page). Did I missed somuething? To which **Server** couldn't a connection be build?

Is there a specific location where arsnova writes its logs? I couldn't find any entrys in the /var/log or in the tomcat logs.

**Comment by deada92** [comment] 2015-11-20 11:23
One more thing...

I checked the initialization logs of tomcat while deploying the backend of arsnova and found this:
```
09:25:31,296  INFO http-bio-8080-exec-14 config.PropertyPlaceholderConfigurer:172 - Loading properties file from class path resource [arsnova.properties.example]
09:25:31,297  INFO http-bio-8080-exec-14 config.PropertyPlaceholderConfigurer:172 - Loading properties file from URL [file:/etc/arsnova/arsnova.properties]
09:25:31,300  INFO http-bio-8080-exec-14 support.PropertySourcesPlaceholderConfigurer:172 - Loading properties file from class path resource [arsnova.properties.example]
09:25:31,300  INFO http-bio-8080-exec-14 support.PropertySourcesPlaceholderConfigurer:172 - Loading properties file from file [/var/apache-tomcat-7.0.34/file:/etc/arsnova/arsnova.properties]
09:25:31,301  WARN http-bio-8080-exec-14 support.PropertySourcesPlaceholderConfigurer:181 - Could not load properties from file [/var/apache-tomcat-7.0.34/file:/etc/arsnova/arsnova.properties]: file:/etc/arsnova/arsnova.properties (No such file or directory)
```

The file 1000% at the location: **/etc/arsnova/arsnova.properties**

**Comment by pcvolkmer** [comment] 2015-11-20 13:20
Since this issue is assigned to me, I took a look at it.
I think this issue is related to some kind of `chroot`. It seams, that Tomcats root directory is set to `/var/apache-tomcat-7.0.34/`, so ARSnova tries to find the property file in this root directory.

You updated your comment. 3 seconds later, Tomcat starts. Is this error still present?

**Comment by deada92** [comment] 2015-11-20 13:27
It logs both things that I have written. Still the error in my comment persists..

**Comment by dgerhardt** [comment] 2015-11-20 14:04
Hey @deada92!

There should not be an issue with the location of your configuration file. Spring looks for `arsnova.properties` in multiple locations an it isn't a problem if it can not be found in one of them.

It looks like you aren't using an Apache HTTPD server in front of Tomcat. While this should work, it isn't officially supported by ARSnova for production systems and might need additional changes in the Tomcat configuration.

The error message you receive from the frontend means that either the ARSnova backend isn't up or that the frontend tries to connect to a wrong address. You can check whether the backend is up by sending a HTTP GET request to `localhost:8080/api/arsnova-config` (`/api` has to be changed in case the backend has been deployed to another path).

**Comment by deada92** [comment] 2015-11-20 14:24
Hey @dgerhardt,

thx for your answer. 

Its true that I dont have a httpd in front of the tomcat, at least not yet. Was trying to get runnin before add the httpd.

The backend seems to be up & running. It returned this:

```
{
"apiPath": "/backend",
"answerOptionLimit": 8,
"mathJaxSrc": "//cdn.mathjax.org/mathjax/2.4-latest/MathJax.js",
"mobilePath": "/mobile",
"parseAnswerOptionFormatting": true,
"maxUploadFilesize": "4194304",
"blogUrl": "https://arsnova.eu/blog/",
"publicPool": {
"levelsEn": "General Education,Highschool,Bachelor,Master,Who Wants to Be a Millionaire,Miscellaneous",
"subjects": "Allgemeines,Anglistik,Architektur,Bauingenieurwesen,Betriebswirtschaftslehre,Biologie,Chemie,Elektrotechnik,Geographie,Geowissenschaften,Germanistik,Geschichtswissenschaft,Informatik,Kunst,Kunstpägogik,Maschinenbau,Mathematik,Medienwissenschaften,Medizin,Musik,Pharmazie,Physik,Psychologie,Rechtswissenschaften,Stadtplanung,Theaterwissenschaften,Theologie,Vermessungswesen,Volkswirtschaftslehre",
"levelsDe": "Allgemeinbildung,Abitur,Bachelor,Master,Wer wird MillionäSonstiges",
"licenses": "CC by - Attribution,CC nc - Non-Commercial,CC nd - No Derivatives,CC sa - Share Alike,CCO - Public Domain,CC by-nd -  Attribution-No Derivatives,CC by-c - Attribution-Non-Commercial,CC by-nc-sa - Attribution-Non-Derivatives-Share Alike,CC by-nc-nd Attribution-Non-Commercial- No Derivatives,GNU GPL - GNU General Public License",
"logoMaxFilesize": "102400"
},
"presenterPath": "/presenter",
"documentationUrl": "https://arsnova.eu/manual/",
"customizationPath": "/customization",
"features": {
"publicPool": true,
"gridSquare": true,
"markdown": true,
"studentsOwnQuestions": true,
"sessionImportExport": true,
"mathJax": true,
"flashcard": true,
"learningProgress": true
},
"grid": "4194304",
"overlayUrl": "https://arsnova.eu/overlay/",
"arsnovaSlogan": "Audience Response System"
}
```

**Comment by dgerhardt** [comment] 2015-11-20 14:45
So the problem is that the frontend tries to contact the backend using the default HTTP port but Tomcat runs on port 8080. You could temporarily change the port in Tomcat's `server.xml` configuration file until you have setup Apache HTTPD. There you modify find the following section:
```
   <Connector executor="tomcatThreadPool"
               port="8080" protocol="HTTP/1.1" ...
```

**Comment by deada92** [comment] 2015-11-20 19:30
that sounds good @dgerhardt ... I will setup apache and do it the right way directly. Thanks for the help. I will write back if everything went goodd!

**Comment by deada92** [comment] 2015-11-25 11:35
Hey @dgerhardt,

here I'm again. I have deployed the applications on a instance where apache + tomcat are already build. Still I have a issue when calling the application.

I will write what I information I have:

**VirtualHost**
```xml
<VirtualHost  134.147.230.219:80>
   ServerName arsnova.rubel.rub.de
    <Proxy *>
            AddDefaultCharset Off
            Order deny,allow
            Deny from none
            Allow from localhost
    </Proxy>
<Location />
    ProxyPass ajp://127.0.0.1:8009/backend/
    ProxyPassReverse ajp://127.0.0.1:8009/backend/
</Location>
</VirtualHost>
```

The httpd error_log had no entrys but the access_log cant find some ressources:
```
[25/Nov/2015:12:01:51 +0100] "GET /favicon.ico HTTP/1.1" 404 301 "http://arsnova.rubel.rub.de/mobile/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
 - - [25/Nov/2015:12:19:26 +0100] "GET /mobile/ HTTP/1.1" 404 301 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
 - - [25/Nov/2015:12:19:26 +0100] "GET /mobile/error/error.css HTTP/1.1" 404 301 "http://arsnova.rubel.rub.de/mobile/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
```

When I call the backend directly from the tomcat manager it displays the same connection error that  I had earlier. Any Idea what I could try next?

**Comment by deada92** [comment] 2015-11-27 09:46
Hey @dgerhardt,

I just got one thing that I don't understand: How does the the /mobile application what path the backend has? As far as I see theres no config for that, right?

**Comment by deada92** [comment] 2015-11-30 16:05
No idea guys?

**Comment by dgerhardt** [comment] 2015-12-01 09:01
You can either setup one Apache `Location` which is a proxy to Tomcat's root or two specific `Location`s for `/backend` and `/mobile`. The latter is recommended in case you have installed additional administrative webapps on Tomcat which should not be publicly accessible.

`api.path` is the proxy path to the backend API which is publically accessible. In your case it should be set to `/backend`. The frontend requests this path by reading /arsnova-config which contains this path. An Apache rewrite has to be set up to make this config accessible from the root path:

```
RewriteEngine On
RewriteRule ^/arsnova-config$ /backend/arsnova-config [PT,L]
```

**Comment by deada92** [comment] 2015-12-01 09:49
Good morning @dgerhardt,

thx for your answer. I have updated my arsnova-propertie file to this:

```xml
# General server settings
################################################################################
# The URL under which the ARSnova server is reachable. Use
# http://localhost:8080 for development.
root-url=http://127.0.0.1:8080/

# The path where the ARSnova API is accessible by clients. By default, this path
# is set to the context path of the backend. If you are running the backend
# behind a proxy server, you might need to set this path manually.
api.path=/backend

# The context paths where the ARSnova modules have been deployed
customization.path=/customization
mobile.path=/mobile
presenter.path=/presenter
```

My Virtualhost looks now like this:

```xml
<VirtualHost  134.147.230.219:80>
   ServerName arsnova.rubel.rub.de
    <Proxy *>
            #AddDefaultCharset Off
            Order deny,allow
            Deny from none
            Allow from localhost
    </Proxy>
RewriteEngine On
RewriteRule ^/arsnova-config$ /backend/arsnova-config [PT,L]
<Location />
    ProxyPass ajp://127.0.0.1:8009/mobile/
    ProxyPassReverse ajp://127.0.0.1:8009/mobile/
</Location>
</VirtualHost>
```

Still I'm getting the connection failed error... :(

**Comment by dgerhardt** [comment] 2015-12-01 11:31
Your configuration:
```
<Location />
    ProxyPass ajp://127.0.0.1:8009/mobile/
    ProxyPassReverse ajp://127.0.0.1:8009/mobile/
</Location>
```

This should either be
```
<Location />
    ProxyPass ajp://127.0.0.1:8009/
    ProxyPassReverse ajp://127.0.0.1:8009/
</Location>
```
or:
```
<Location /mobile/>
    ProxyPass ajp://127.0.0.1:8009/mobile/
    ProxyPassReverse ajp://127.0.0.1:8009/mobile/
</Location>
<Location /backend/>
    ProxyPass ajp://127.0.0.1:8009/backend/
    ProxyPassReverse ajp://127.0.0.1:8009/backend/
</Location>
```

**Comment by deada92** [comment] 2015-12-01 12:03
My Virtualhost:

```xml
<VirtualHost  134.147.230.219:80>
   ServerName arsnova.rubel.rub.de
    <Proxy *>
            #AddDefaultCharset Off
            Order deny,allow
            Deny from none
            Allow from localhost
    </Proxy>
<Location /mobile/>
    ProxyPass ajp://127.0.0.1:8009/mobile/
    ProxyPassReverse ajp://127.0.0.1:8009/mobile/
</Location>
<Location /backend/>
    ProxyPass ajp://127.0.0.1:8009/backend/
    ProxyPassReverse ajp://127.0.0.1:8009/backend/
</Location>
</VirtualHost>
```

Well now I get a 404 when I access arsnova.rubel.rub.de with this VH.

**Comment by dgerhardt** [comment] 2015-12-01 12:13
A `Redirect / https://arsnova.rubel.rub.de/mobile/` should do the trick.

But you still have to make sure that the configuration is accessible at https://arsnova.rubel.rub.de/arsnova-config. See my comment regarding the URL rewrite.

**Comment by deada92** [comment] 2015-12-01 12:41
I cant thank you enough @dgerhardt! Whenever you are in Bochum u have a free drink on me ;)

For everyone else thats my final VH:

```xml
</VirtualHost>
#Arsnova VH / Do not change
<VirtualHost  134.147.230.219:80>
   ServerName arsnova.rubel.rub.de
    <Proxy *>
            #AddDefaultCharset Off
            Order deny,allow
            Deny from none
            Allow from localhost
    </Proxy>
<Location /arsnova-config>
    ProxyPass ajp://127.0.0.1:8009/backend/arsnova-config
    ProxyPassReverse ajp://127.0.0.1:8009/backend/arsnova-config
</Location>

<Location /mobile/>
    ProxyPass ajp://127.0.0.1:8009/mobile/
    ProxyPassReverse ajp://127.0.0.1:8009/mobile/
</Location>

<Location /backend/>
    ProxyPass ajp://127.0.0.1:8009/backend/
    ProxyPassReverse ajp://127.0.0.1:8009/backend/
</Location>
Redirect / http://arsnova.rubel.rub.de/mobile/
</VirtualHost>
```

**Closed** 2015-12-03 07:36 UTC
Labels: question
